library space;

import 'dart:html';
import 'dart:collection';
import 'dart:async';
import 'dart:math';
import 'dart:isolate';
import 'package:siege_engine/siege_engine.dart';
import 'package:vector_math/vector_math.dart';
import 'package:pathos/path.dart' as path;
import "package:json_object/json_object.dart";

part 'components/basic/acceleration_component.dart';
part 'components/basic/position_component.dart';
part 'components/basic/image_component.dart';
part 'components/basic/rotation_component.dart';
part 'components/basic/velocity_component.dart';
part 'components/basic/camera_centering_component.dart';
part 'components/basic/attach_component.dart';
part 'components/basic/collision_component.dart';
part 'components/basic/alpha_component.dart';
part 'components/basic/image_scaling_component.dart';
part 'components/steering/follower_component.dart';
part 'components/steering/wanderer_component.dart';
part 'components/steering/path_follower_component.dart';
part 'components/weapon/weapon_trigger_component.dart';
part 'components/weapon/repeating_weapon_component.dart';
part 'components/weapon/single_direction_weapon_component.dart';
part 'components/weapon/weapon_attributes_component.dart';
part 'components/weapon/predicting_weapon_component.dart';
part 'components/identifier/enemy_component.dart';
part 'components/identifier/player_component.dart';
part 'components/identifier/target_component.dart';
part 'components/identifier/player_weapon_component.dart';
part 'components/identifier/enemy_weapon_component.dart';
part 'utils/canvas_manager.dart';
part 'utils/scene_manager.dart';
part 'utils/game_settings.dart';
part 'utils/id_manager.dart';
part 'utils/entity_builder.dart';
part 'utils/game_status.dart';
part 'utils/input_manager.dart';
part 'utils/asset_manager.dart';
part 'utils/ship_base.dart';
part 'utils/random_ship_generator.dart';
part 'scenes/scene.dart';
part 'scenes/main_menu_scene.dart';
part 'scenes/game_scene.dart';
part 'scenes/loading_scene.dart';
part 'systems/image_rendering_system.dart';
part 'systems/movement_system.dart';
part 'systems/follower_system.dart';
part 'systems/entity_spawning_system.dart';
part 'systems/debugging_system.dart';
part 'systems/wanderer_system.dart';
part 'systems/path_follower_system.dart';
part 'systems/attach_system.dart';
part 'systems/collision_system.dart';
part 'systems/ui_system.dart';
part 'systems/weapon/weapon_triggering_system.dart';
part 'systems/weapon/weapon_shooting_system.dart';
part 'systems/weapon/target_predicting_system.dart';

GameSettings settings;
CanvasManager canvasManager;
SceneManager sceneManager;
InputManager inputManager;
IdManager idManager;
AssetManager assetManager;

void main() {
  settings = new GameSettings();
  idManager = new IdManager();
  canvasManager = new CanvasManager(query("#space_game_canvas"));
  inputManager = new InputManager();
  sceneManager = new SceneManager();
  assetManager = new AssetManager();
  sceneManager.run();
  sceneManager.addScene("loading", new LoadingScene());
  sceneManager.changeScene("loading");
}